# Generated by Django 4.2.5 on 2023-09-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('netflix', models.BooleanField()),
                ('hbo', models.BooleanField()),
                ('amazon', models.BooleanField()),
                ('player', models.BooleanField()),
            ],
        ),
    ]
