# Generated by Django 4.2.5 on 2023-09-14 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mixer', '0002_alter_movie_amazon_alter_movie_hbo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='amazon',
        ),
    ]
