# Generated by Django 4.2.5 on 2023-09-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixer', '0003_remove_movie_amazon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='hbo',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='netflix',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='player',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='url',
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
