# Generated by Django 4.2.5 on 2023-09-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixer', '0004_remove_movie_hbo_remove_movie_netflix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=200, verbose_name=''),
        ),
    ]
